FROM maven:3.9-eclipse-temurin-17 as build
ENV HOME=/usr/app
RUN mkdir -p $HOME
WORKDIR $HOME

ADD pom.xml $HOME
ADD oom/pom.xml $HOME/oom/pom.xml
ADD caller/pom.xml $HOME/caller/pom.xml
ADD callee/pom.xml $HOME/callee/pom.xml
ADD callee-with-db/pom.xml $HOME/callee-with-db/pom.xml

RUN mvn -pl oom verify --fail-never
ADD oom $HOME/oom
RUN mvn -DskipTests -pl oom install

RUN mvn -pl caller verify --fail-never
ADD caller $HOME/caller
RUN mvn -DskipTests -pl caller install

RUN mvn -pl callee verify --fail-never
ADD callee $HOME/callee
RUN mvn -DskipTests -pl callee install

RUN mvn -pl callee-with-db verify --fail-never
ADD callee-with-db $HOME/callee-with-db
RUN mvn -DskipTests -pl callee-with-db install

RUN mvn -DskipTests -pl oom,callee,caller,callee-with-db package

FROM openjdk:17-jdk-alpine
COPY --from=build /usr/app/callee/target/callee-0.0.1.jar /app/callee-0.0.1.jar

RUN mkdir -p /whatap
COPY --from=build /usr/app/callee/whatap.conf /whatap

COPY --from=whatap/kube_mon /data/agent/micro/whatap.agent.kube.jar /whatap

CMD ["java", "-javaagent:/whatap/whatap.agent.kube.jar","-Dwhatap.micro.enabled=true","--add-opens=java.base/java.lang=ALL-UNNAMED","-jar", "/app/callee-0.0.1.jar"]